version: '3.2'
networks:
  app_net:
    external:
      name: default_net
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    privileged: true
    container_name: mongodb
    networks:
      - app_net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=abc123456
    volumes:
      - type: bind
        source: ./mongodb/data
        target: /data/db
    ports:
      - "27017:27017"
  redis:
    image: 'bitnami/redis:7.4.1'
    restart: always
    privileged: true
    container_name: redis
    networks:
      - app_net
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=abc123456
    volumes:
      - ./bitnami/redis/data:/bitnami/redis/data
    ports:
      - "6379:6379"


