<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.kingman</groupId>
        <artifactId>companion-module</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>companion-module-log</artifactId>
    <name>companion-module-log</name>
    <description>日志模块：每日情绪日志、AI建议</description>

    <dependencies>
        <dependency>
            <groupId>com.kingman</groupId>
            <artifactId>companion-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kingman</groupId>
            <artifactId>companion-component</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
